### ISSUE TITLE
$parser->getRegisterableDomain() can't parse https://www.google.com/search correctly

### ISSUE THREAD

**Issue by samsonasik** [jeremykendall/php-domain-parser#186]
```php
echo $parser->getRegisterableDomain('https://www.google.com/search');
```
got result: `google.com/search`

```php
echo $parser->parseUrl($url)->host->registerableDomain
```
got result: `google.com`

**Comment by thumbtech** [comment]
getRegisterableDomain assumes it is passed "host", not "url".
host => www.google.com
url => https://www.google.com/search

Confusing for sure. Personally, I think it should be made private function since its results are totally unpredictable unless passed a real host value, which only parseUrl can reliably produce in this library.

Always use your $parser->parseUrl($url)->host->registerableDomain instead!
