### ISSUE TITLE
Any subdomain from blogspot.com returns that is not a subdomain

### ISSUE THREAD

**Issue by adrianb1890** [jeremykendall/php-domain-parser#206]
If you test any subdomain from blogspot.com will return that is not a subdomain. Example:
efilnikufesin-in-hell.blogspot.com
       
	function is_subdomain($domain) {
		require_once($_SERVER['DOCUMENT_ROOT'].'/lib/vendor/autoload.php');
		$pslManager = new Pdp\PublicSuffixListManager();
		$parser = new Pdp\Parser($pslManager->getList());
		$subdomain = $parser->getSubdomain($domain);
		if(!empty($subdomain)) {
			return true;
		}
		return false;
	}
       is_subdomain('efilnikufesin-in-hell.blogspot.com');
      // return false

**Comment by nyamsprod** [comment]
@adrianb1890 Hi, this issue is resolve in the new version of Pdp which we are about to release it the following days. You can already test this using the branch https://github.com/jeremykendall/php-domain-parser/tree/v5

```php
<?php

use Pdp\Manager;
use Pdp\Cache;
use Pdp\CurlHttpClient;
use Pdp\Rules;

$manager = new Manager(new Cache(), new CurlHttpClient());
$rules = $manager->getRules();
$domain = $rules->resolve('efilnikufesin-in-hell.blogspot.com', Rules::ICANN_DOMAINS);
$domain->getSubDomain(); // returns 'efilnikufesin-in-hell'
```

The previous version did not take into account the distinction between PRIVATE and ICANN domains.

**Comment by nyamsprod** [comment]
the new version has been released. And we can not fix this one in version 3 has it would introduce BC break. I'll close this issue as it has been fixed in a stable release
