### ISSUE TITLE
The host `องค๜กร` is invalid : a label or domain name contains disallowed characters.

### ISSUE THREAD

**Issue by tuxado** [jeremykendall/php-domain-parser#216]
I have this errors with symfony any suggestions pls?

`
use Pdp\Manager;
use Pdp\Cache;

			$guzzleAdapter = new GuzzleHttpClientAdapter(new GuzzleClient());

			$cache = new Cache();

			$manager = new Manager($cache, $guzzleAdapter);
			$manager->refreshRules();
			
			$rules = $manager->getRules();
			$domain = $rules->resolve('www.github.com');

`

[Pdp\Exception]
The host `องค๜กร` is invalid : a label or domain name contains disallowed characters.

**Comment by nyamsprod** [comment]
@tuxado thanks for using the library. Unfortunately this message mean that your internationalized domain name can not be converted into an ASCII one using the IDNA UTS46 algorithm. The exception message indicate that your domain name contains a character that can not be converted. There's not much we can do about that.

**Comment by tuxado** [comment]
@nyamsprod  hi, 

it seem that the problem come from the PLS file content encoding i add utf8_decode to the PLS content and the error gone but another error has been appear relative to the parse of the PLS file and there is the trace : 

string(10) "idnToAscii"
string(2) "sh"
string(10) "idnToAscii"
string(3) "now"

[Symfony\Component\Debug\Exception\FatalThrowableError]
Type error: json_decode() expects parameter 1 to be string, boolean given

i suggest to add the PLS as php array file to prevent the encoding problem and optimise the performance

**Comment by nyamsprod** [comment]
@tuxado could you provide a simple example for your issue because the first code you provided seems to be truncated so I can not reproduce the issue. 
FWIW the cache file should not contains any utf8 character as the public suffix content is converted into ascii form prior to being saved.

**Comment by tuxado** [comment]
@nyamsprod 

yes plz see the  attacchment

[source.txt](https://github.com/jeremykendall/php-domain-parser/files/1782355/source.txt)

i have add a utf8_decode  at the converter file  and it work : 
```

    public function convert(string $content): array
    {
        $rules = [Rules::ICANN_DOMAINS => [], Rules::PRIVATE_DOMAINS => []];
        $file = new SplTempFileObject();
        $file->fwrite($content);
        $file->setFlags(SplTempFileObject::DROP_NEW_LINE | SplTempFileObject::READ_AHEAD | SplTempFileObject::SKIP_EMPTY);
        $section = '';
        foreach ($file as $line) {
			$line = utf8_decode($line);
            $section = $this->getSection($section, $line);
            if ('' !== $section && false === strpos($line, '//')) {
                $rules[$section] = $this->addRule($rules[$section], explode('.', $line));
            }
        }

        return $rules;
    }

```

an otther problem when we try  to resolve  url llike http://www.github.com/some/path the  result are horible  maybe adding trim(parse_url('http://www.github.com/some/path', PHP_URL_HOST), '/') to the resolve  function  to make  sure that the url given to the  resolve are tthe host

**Comment by nyamsprod** [comment]
@tuxado here's a simple snippet using the code out of the box:

```php
<?php

use GuzzleHttp\Client as GuzzleClient;
use Pdp\Manager;
use Pdp\Cache;
use Pdp\CurlHttpClient;
use Pdp\Rules;
use Pdp\HttpClient;
use Pdp\HttpClientException;
use Symfony\Component\Cache\Simple\PDOCache;

require 'vendor/autoload.php';

final class GuzzleHttpClientAdapter implements HttpClient
{
    private $client;

    public function __construct(GuzzleClient $client)
    {
        $this->client = $client;
    }

    public function getContent(string $url): string
    {
        try {
            return $client->get($url)->getBody()->getContents();
        } catch (Throwable $e) {
            throw new HttpClientException($e->getMessage(), $e->getCode(), $e);
        }
    }
}

$rules = Rules::createFromString('https://publicsuffix.org/list/public_suffix_list.dat');
var_dump($rules->resolve('www.UlB.Ac.be')); // no cache

$rules = (new Manager(new Cache(), new CurlHttpClient()))->getRules();
var_dump($rules->resolve('www.UlB.Ac.be')); // default cache + curl http client

$guzzleAdapter = new GuzzleHttpClientAdapter(new GuzzleClient());
$rules = (new Manager(new Cache(), $guzzleAdapter))->getRules();
var_dump($rules->resolve('www.UlB.Ac.be')); //default cache + guzzle http client
```
I've bypassed the cache, changed the Http client but I can not reproduced your bug. I suspect the error comes from your cache or how you setup your HTTP client but *not* from the library itself :'( .

For your other issue, the library does not extract the host from your submitted URL you have the resposability to submit a correct domain name. URL parsing is now out of scope for the library.

**Comment by tuxado** [comment]
@nyamsprod 

thanks for the help, it is possible on windows with php 7 and  using command line console, i have this problem of encoding. so using utf8_decode twice on the content seems to solve it.

**Comment by dlindberg** [comment]
I've been trying to trace what turns out to be a similar problem I'm having on my system, it seems that, unfortunately, double utf8_decode renders anything not in the ASCII character set as a`?` so eliminates a significant number of TDLs from being able to match properly.

For me, at least, switching to the guzzle curl adaptor did actually resolve at least part of the issue. The first test case resolved. The second two failed on the encoding issue.

placing `$part = urlencode($part);` into  `Converter::addRule` right before `$part = $this->idnToAscii(strtolower($part));` seems to allow the cache to be successfully stored, and seems to work. But I don't know if that has any sort of negative knock on effect that I'm just not seeing.

Out of curiosity, what version of PHP 7 are you using? I'm using 7.2.3 and also trying to use this with the command line version.

**Comment by nyamsprod** [comment]
@dlindberg You should not add any urlencode/urldecoding call in the Converter class this is the responsability of the idnToAscii method to convert the PLS info into correct ascii characters. A simple way to understand your issue would be to:

manually donwload the PLS and then use the named constructor `Rules::createFromPath` to test if the data is correctly loaded. If the answer is yes then it means that the issue is the HTTP Client or the Cache Backend. Either way do not add any urlencode/decode/uf8decode into the mix has it would result in error.

**Comment by dlindberg** [comment]
Thanks, I was thinking that might short circuit something important that I wasn't noticing just yet. I fiddled with this a bit more, starting with the sample code test you sent @tuxado, and noticed that what I thought was working yesterday was actually a failure, the result wasn't matching the expected result even though there was nothing in the code path to throw an exception.

I re-read the test code and noticed it uses `Rules::createFromString` not `Rules::createFromPath`. When I use `Rules::createFromPath` all three tests fail with the same exception. So I tried your suggestion and manually download the PLS.

```php
$rules = Rules::createFromPath('public_suffix_list.dat');
var_dump($rules->resolve('www.UlB.Ac.be'));
```

I got the same error I got from the fopen() and curl() methods from the remote data source. This was really starting to seem odd, so I tried making the text file directly return a php string using a return statement (and of course escaping the necessary characters) and using the `Rules::createFromString` method:

```php
$rules = Rules::createFromString(stripcslashes(require_once ('public_suffix_list.php')));
echo json_encode($rules->resolve('www.UlB.Ac.be', Rules::ALL_DOMAINS), JSON_PRETTY_PRINT);
```

It also returns the same error:

```
PHP Fatal error:  Uncaught Pdp\Exception: The host `a�roport` is invalid : a label or domain name contains disallowed characters. in /Users/<user>/Projects/example/vendor/jeremykendall/php-domain-parser/src/IDNAConverterTrait.php:84
Stack trace:
#0 /Users/<user>/Projects/example/vendor/jeremykendall/php-domain-parser/src/Converter.php(107): Pdp\Converter->idnToAscii('a\xE3\xA9roport')
#1 /Users/<user>/Projects/example/vendor/jeremykendall/php-domain-parser/src/Converter.php(119): Pdp\Converter->addRule(Array, Array)
#2 /Users/<user>/Projects/example/vendor/jeremykendall/php-domain-parser/src/Converter.php(46): Pdp\Converter->addRule(Array, Array)
#3 /Users/<user>/Projects/example/vendor/jeremykendall/php-domain-parser/src/Rules.php(67): Pdp\Converter->convert('// This Source ...')
#4 /Users/<user>/Projects/example/example(106): Pdp\Rules::createFromString('// This Source ...')
#5 {main}
  thrown in /Users/<user>/Projects/example/vendor/jeremykendall/php-domain-parser/src/IDNAConverterTrait.php on line 84

Fatal error: Uncaught Pdp\Exception: The host `a�roport` is invalid : a label or domain name contains disallowed characters. in /Users/<user>/Projects/example/vendor/jeremykendall/php-domain-parser/src/IDNAConverterTrait.php on line 84

Pdp\Exception: The host `a�roport` is invalid : a label or domain name contains disallowed characters. in /Users/<user>/Projects/example/vendor/jeremykendall/php-domain-parser/src/IDNAConverterTrait.php on line 84

Call Stack:
    0.0005     397896   1. {main}() /Users/<user>/Projects/example/example:0
    0.0056    1134712   2. Pdp\Rules::createFromString() /Users/<user>/Projects/example/example:106
    0.0060    1173984   3. Pdp\Converter->convert() /Users/<user>/Projects/example/vendor/jeremykendall/php-domain-parser/src/Rules.php:67
    0.0179    1449432   4. Pdp\Converter->addRule() /Users/<user>/Projects/example/vendor/jeremykendall/php-domain-parser/src/Converter.php:46
    0.0179    1449456   5. Pdp\Converter->addRule() /Users/<user>/Projects/example/vendor/jeremykendall/php-domain-parser/src/Converter.php:119
    0.0180    1449896   6. Pdp\Converter->idnToAscii() /Users/<user>/Projects/example/vendor/jeremykendall/php-domain-parser/src/Converter.php:107
```

So I was really scratching my head at this point and took a hard look at the `IDNAConverterTrait` and it really seems as if it expects IDN Punycode or us-ascii as its input instead of UTF-8? If that's not it, then I really have no idea what the issue is because it doesn't seem like a curl issue anymore either. I tried asking publicsuffix.org to send a us-ascii file instead of UTF-8 using postman, but it didn't want to do that, so that doesn't account for why it works for you and not for us. I decided to just see what happens if I forced things to Punycode. I  used [mso/idna-convert](https://idnaconv.net/index.html) for the job because it can just Punycode non ASCII characters without encoding a bunch of characters that need to be left alone for the rule parsing method to work correctly.

```PHP
#!/usr/bin/env php
<?php

use Pdp\Rules;
use Mso\IdnaConvert\IdnaConvert;

require_once __DIR__ . '/vendor/autoload.php';

$IDN = new IdnaConvert();

$lines = [];

foreach (file('public_suffix_list.dat') as $line) {
    if (false === strpos($line, '//')) {
        $lines[] = $IDN->encode(trim($line), 'utf8');
    } else {
        $lines[] = $line;
    }
}

$string = implode(PHP_EOL, $lines);

$rules = Rules::createFromString($string);

echo json_encode($rules->resolve('www.UlB.Ac.be', Rules::ALL_DOMAINS), JSON_PRETTY_PRINT);
```

And that does indeed return a test passing output:

```JSON
{
    "domain": "www.ulb.ac.be",
    "registrableDomain": "ulb.ac.be",
    "subDomain": "www",
    "publicSuffix": "ac.be",
    "isKnown": true,
    "isICANN": true,
    "isPrivate": false
}
```

This seems like it is still not a particularly robust solution though. While it does allow php-domain-parser (on my system) to return correct results against the entire [public suffix test data](https://raw.githubusercontent.com/publicsuffix/list/master/tests/test_psl.txt) set, it Errors 3 unit tests and fails 2 more when I hack the solution into `Converter::convert`. So it is clearly still short circuiting something.

**Comment by nyamsprod** [comment]
@dlindberg I've manage to find and reproduce the error. And TBH the develop branch response is better than the master one. here's how I've reproduced your bug.
```php
<?php

use Pdp\Converter;

require 'vendor/autoload.php';

$psl = <<<EOF
// ===BEGIN ICANN DOMAINS===
ci
aéroport.ci
// ===END ICANN DOMAINS===
// ===BEGIN PRIVATE DOMAINS===
bar
a\xE3\xA9roport.bar
// ===END PRIVATE DOMAINS===
EOF;

try {
    var_dump((new Converter())->convert($psl));
} catch (Throwable $e) {
    echo '<pre>', $e->getMessage(), PHP_EOL, $e->getTraceAsString(), PHP_EOL;
}
```
The bug you are experiencing is because for some unkown reason beyond the package capabilities, your PSL copy seems to have converted `aéroport.bar` into  `a\xE3\xA9roport.bar` **prior** to being submitted for conversion. On the dev branch the issue is detected and therefore a `Pdp\Exception` is thrown while the conversion silently failed on the current stable branch (ie: 5.2.0).

So to me the fix is already in place on the dev branch and you should definitely look into how and why the encoding is done on your PSL file prior to be submitted to the package ? Once you have find the culprit everything else should work out of the box.

**Comment by dlindberg** [comment]
@nyamsprod thanks, there is no way I would have gotten this far without the better error messages in the dev branch. Your test case just helped me "find" the problem too. If I remove the `a\xE3\xA9roport.bar` line and run the sample code through the web PHP parser it succeeds. If I run the exact same code through the command line parser it fails, error as described above.

At first I hoped it was a version or setting miss match, but with both the php-cli and php-fpm versions configure the same way the cli version still errors. This seems to line up with @tuxado 's experience too where the cli version fails. There is certainly a very strange behavior that I'm not quite able to pin down, but it seems at least possible it is a bug in the php cli parser itself.

At this point, I've found that in a code path that does not include a call to:
```php
$this->rules = Rules::createFromString($string);
```

Importing and then immediately dumping the PSL results in a properly encoded a clean no diff version of the PSL that went in.

If I make a call to `Rules::create` the dump of the PSL file is completely mangled. Even if I dump it before the call to `Rules::create` and even if I dump it after importing the PSL twice into two separate variables that I flush the output buffer on before I call `Rules::create`

```php
#!/usr/bin/env php
<?php

use Pdp\Rules;

require_once 'vendor/autoload.php';

$string = stripcslashes((require'psl.php'));
$strung = stripcslashes((require'psl.php'));
ob_start();
echo $string;
ob_end_flush();
flush();
$this->rules = Rules::createFromString($strung);

```

Will fail and dump a mangled PSL file 

```php
#!/usr/bin/env php
<?php

use Pdp\Rules;

require_once 'vendor/autoload.php';

$string = stripcslashes((require'psl.php'));
$strung = stripcslashes((require'psl.php'));
ob_start();
echo $string;
ob_end_flush();
flush();
```

Will, well, do what one would expect it to do. When the same test case is modified for the PHP-FPM parser:

```PHP
<?php

use Pdp\Rules;

require_once  '../vendor/autoload.php';

$string = stripcslashes((require'../psl.php'));
$strung = stripcslashes((require'../psl.php'));
ob_start();
echo '<pre>';
echo $string;
ob_end_flush();
flush();
$this->rules = Rules::createFromString($strung);
```

It is also just fine, a good PSL file is output to the browser.

 I'll report back if / when I can figure out how the CLI version of PHP to do this correctly.

**Comment by dlindberg** [comment]
Found it, pull request submitted.
