### ISSUE TITLE
Error with https://name:pwd@domain.com/

### ISSUE THREAD

**Issue by Machou** [jeremykendall/php-domain-parser#331]
## Issue summary

When i try to parser this domains :+1: 

`https://validator.w3.org/#validate_by_input`
`http(s)://login:pwd@domain.com/`

```php
<?php
$publicSuffixList = Rules::fromPath('geo/public_suffix_list.dat');
$domain = Domain::fromIDNA2008($_REQUEST['domain']);
$domainResolve = $publicSuffixList->resolve($domain);

echo $domainResolve->registrableDomain()->toString();
```

```
Fatal error: Uncaught Pdp\SyntaxError:

The host `login:td3dt1737d54sjdid04i@login.domain.io` is invalid: it contains invalid characters.

in /home/blok/composer/vendor/jeremykendall/php-domain-parser/src/SyntaxError.php:21

Stack trace: #0 /home/blok/composer/vendor/jeremykendall/php-domain-parser/src/Domain.php(149):Pdp\SyntaxError::dueToInvalidCharacters('login:td3dt1...')

#1 /home/blok/composer/vendor/jeremykendall/php-domain-parser/src/Domain.php(103): Pdp\Domain->parseValue('name:td3dt1...')
#2 /home/blok/composer/vendor/jeremykendall/php-domain-parser/src/Domain.php(62): Pdp\Domain->parseDomain('name:td3dt1...')
#3 /home/blok/composer/vendor/jeremykendall/php-domain-parser/src/Domain.php(87): Pdp\Domain->__construct('IDNA_2008', 'name:td3dt1...')
#4 /home/blok/www/projets/dns.php(19): Pdp\Domain::fromIDNA2008('name:td3dt1...')
#5 {main} thrown in /home/blok/composer/vendor/jeremykendall/php-domain-parser/src/SyntaxError.php on line 21
```

**Comment by nyamsprod** [comment]
@Machou thanks for using the library.

I believe the error is self explanatory `login:td3dt1737d54sjdid04i@login.domain.io` is not a valid host. The parser except to receive a Host not an authoriyt component like the one reported by the exception message.

so instead of submitting `login:td3dt1737d54sjdid04i@login.domain.io` you should have submitted `login.domain.io` without the user-info component of your URI.

You should use PHP's built-in function `parse_url` or a dedicated URI parsing package found on packagist for instance if you want to correctly extract the host part of you URI.

Hopes this answer your question.

**Comment by Machou** [comment]
I thought the bookstore could clean itself, I misunderstood =)
