### ISSUE TITLE
old version 1.4 with composer

### ISSUE THREAD

**Issue by allotmentandy** [jeremykendall/php-domain-parser#345]
i installed it with 

`composer require jeremykendall/php-domain-parser`

but that gave me version 1.4 and the examples didnt work

i changed the version in the composer.json to 6.1 and it worked a treat after a composer update

        "jeremykendall/php-domain-parser": "^6.1",

**Comment by nyamsprod** [comment]
@allotmentandy it's a known issue due to how the package is declared prior to version 5.
if it has installed version 1.4.x it means that some dependencies do not resolve as expected. The issue with the explanation is [now pinned](https://github.com/jeremykendall/php-domain-parser/issues/344)

**Comment by allotmentandy** [comment]
i am not clear, is it an issue with composer version I used? 

or is it an issue with my composer.json / php environment? i didnt have php8.0-intl installed when i tried the first time.

**Comment by nyamsprod** [comment]
No it's how the package composer.json was generated before version 5.0.

For instance as an example let's say you are on PHP8.0 and you do not have `intl` installed the best version composer will then load is 1.4.4 which is a bummer. so there's nothing you can do except explicitly requiring version 6 as you did afterward.

Again this is just one example where this can happen because of version constraints.

**Comment by allotmentandy** [comment]
thanks for the reply.
