### ISSUE TITLE
Public Suffix List as a package

### ISSUE THREAD

**Issue by szepeviktor** [jeremykendall/php-domain-parser#357]
## Issue summary

Are there plans to release Public Suffix List as a Composer package?

**Comment by nyamsprod** [comment]
Hi @szepeviktor sorry but I fail to understand your question. The list does not need any package as it is maintained and made publicly available by Mozilla. Or you are thinking of something else 🤔

**Comment by szepeviktor** [comment]
When I use php-domain-parser I need to set up a mechanism to update the list.
We could release the list as a Composer package with weekly updates.

**Comment by nyamsprod** [comment]
Previous versions of the package use to offer a cache mechanism. It was removed because the cache was never in sync with the Mozilla list or with the application settings. If you implement the new caching system as explain in the doc you should tbe fine.
Also there's a companion package for Laravel which can be set for doing jist that.

**Comment by szepeviktor** [comment]
I am talking about making the cache mechanism unnecessary by releasing the list as a package.

**Comment by nyamsprod** [comment]
That's a bad idea because it gives a false sense a accuracy

**Comment by nyamsprod** [comment]
as an example see how the laravel package manage what you are asking: 

https://distortedfusion.com/docs/kevindierkx/laravel-domain-parser/getting-started#configuration

to me that's how you should do it. Because you get the full control over the cache and when and how to update it. And since the integration is done on the. application level on daily usage you can completely forget about the cache and the copy.

**Comment by szepeviktor** [comment]
Okay. So you are against publishing the list as a package.
