### ISSUE TITLE
using only  ICANN DOMAINS and negelecting PRIVATE DOMAINS

### ISSUE THREAD

**Issue by sandipp** [jeremykendall/php-domain-parser#41]
I want to extract domain from following url

     url = "http://s3.amazonaws.com/cdn.foxydeal.com/sf/v6/main.js"
     domain = "amazonaws.com"
     subdomain = "s3"
But I am getting following values 

    domain = ""
    subdomain = ""
this is happening because, in this list 
`https://publicsuffix.org/list/effective_tld_names.dat`
`s3.amazonaws.com` is marked as public suffix in PRIVATE DOMAINS sections. is there any ways to neglect private domains sections.

**Comment by jeremykendall** [comment]
I can appreciate you'd like to see some different output from the parser for that URL, but it's being parsed correctly in this context. The output you're getting, as you noted above, is appropriate based on the content of the Public Suffix List and the [parsing algorithm outlined at publicsuffix.org](https://publicsuffix.org/list/).

Since this library is designed specifically for Public Suffix List based domain parsing, I won't be making any changes related to private domains.

For reference, here is the full output of parsing `http://s3.amazonaws.com/cdn.foxydeal.com/sf/v6/main.js`:

```
$ ./bin/parse http://s3.amazonaws.com/cdn.foxydeal.com/sf/v6/main.js
Array
(
    [scheme] => http
    [user] => 
    [pass] => 
    [host] => s3.amazonaws.com
    [subdomain] => 
    [registerableDomain] => 
    [publicSuffix] => s3.amazonaws.com
    [port] => 
    [path] => /cdn.foxydeal.com/sf/v6/main.js
    [query] => 
    [fragment] => 
)
Host: http://s3.amazonaws.com/cdn.foxydeal.com/sf/v6/main.js
```

**Comment by sandipp** [comment]
I have tested `purl` library to solve this problem, using `purl` its not solved directly.
But I did following (wired) workarund to make it working, adding here for reference,

        $url = new \Purl\Url($url);
        $mainDomain = $parser->getRegisterableDomain($url);
        $subdomain = $parser->getSubdomain($url);

and this is working giving me following output 
     
     $domain = "http://s3.amazonaws.com/"
     $subdomain = "http://s3"

I will try to fix this only using php-domain-parser library.

**Comment by jeremykendall** [comment]
I'm getting a different result than you are, @sandipp.

```php
$url = 'http://s3.amazonaws.com/cdn.foxydeal.com/sf/v6/main.js';
$url = new \Purl\Url($url);

var_dump($url->publicSuffix); // string(16) "s3.amazonaws.com"
var_dump($url->registerableDomain); // null
var_dump($url->subdomain); // null
var_dump($url->canonical); // string(47) "com.amazonaws.s3/cdn.foxydeal.com/sf/v6/main.js"
```

Purl uses PHP Domain Parser (currently the 1.3 branch) under the hood. Since it parses the domain in the same manner as PDP, I think you're in for a bad time if you try to modify the parsing to meet the needs of your use case. You might try coding something custom in order to meet your needs, perhaps using Purl or PDP as a dependency.

**Comment by sandipp** [comment]
@jeremykendall, please notice my code.

I am using both `purl` and `PHP Domain Parser` and its working.
(I am aware of that `Purl` is dependant on `PHP Domain Parser`.) 

    $url = new \Purl\Url($url);
    $mainDomain = $parser->getRegisterableDomain($url);
    $subdomain = $parser->getSubdomain($url);
Your absolutely right about custom solution, I might work on it in weekend.
Thank you.
